# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
    "git",
		"gh",
		"hyprland",
		"kitty",
		"neovim-nightly",
		"oh-my-posh-bin",
		"pnpm",
		"zoxide",
		"fzf",
		"eza",
		"zsh",
	  "stow",
		"nodejs",
		"npm",
		"git-delta",
		"keyd",
		"zen-browser-bin",
		"vicinae-bin",
		"yazi"
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    # "com.github.tchx84.Flatseal",
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
    # "bacon",
]
