# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
# Terminal
    "git",
		"github-cli",
		"kitty",
		"neovim-nightly",
		"oh-my-posh-bin",
		"pnpm",
		"zoxide",
		"fzf",
		"eza",
		"yazi",
		"zsh",
	  "stow",
		"nodejs",
		"npm",
		"git-delta",
		"keyd",
		"man",
# Gtk
		"layan-gtk-theme",
# Fonts
    "ttf-jetbrains-mono-nerd",
#Desktop*
		"hyprland",
		"hyprpaper",
		"hypridle",
		"hyprsunset",
		"waybar",
		"vicinae-bin",
# Hobbies
    "godot",
    "blender",
		"zen-browser-bin",
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    # "com.github.tchx84.Flatseal",
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
    # "bacon",
]
